import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const pluginRoot = join(import.meta.dirname, '..');

describe('adapter build', () => {
  it('build-adapters.mjs generates adapter files', () => {
    const result = execFileSync('node', [
      join(pluginRoot, 'scripts/build-adapters.mjs'),
    ], { encoding: 'utf8', cwd: pluginRoot });
    assert.ok(result.includes('Built'), `Expected success output, got: ${result}`);
  });

  it('second build produces no content drift', () => {
    // First build
    execFileSync('node', [
      join(pluginRoot, 'scripts/build-adapters.mjs'),
    ], { encoding: 'utf8', cwd: pluginRoot });

    // Check mode — should pass with no drift
    const checkResult = execFileSync('node', [
      join(pluginRoot, 'scripts/build-adapters.mjs'),
      '--check',
    ], { encoding: 'utf8', cwd: pluginRoot });
    assert.ok(checkResult.includes('No drift'), `Expected no drift, got: ${checkResult}`);
  });

  it('codex adapter has all skill files', () => {
    const skills = ['e2e-test-help', 'e2e-test', 'e2e-test-author', 'e2e-test-review', 'e2e-test-repair'];
    for (const skill of skills) {
      const path = join(pluginRoot, 'adapters', 'codex', 'skills', skill, 'SKILL.md');
      const content = readFileSync(path, 'utf8');
      assert.ok(content.startsWith('---\n'), `codex/${skill} must have frontmatter`);
    }
  });

  it('claude adapter has all skill files', () => {
    const skills = ['e2e-test-help', 'e2e-test', 'e2e-test-author', 'e2e-test-review', 'e2e-test-repair'];
    for (const skill of skills) {
      const path = join(pluginRoot, 'adapters', 'claude', 'skills', skill, 'SKILL.md');
      const content = readFileSync(path, 'utf8');
      assert.ok(content.startsWith('---\n'), `claude/${skill} must have frontmatter`);
    }
  });

  it('claude adapter has plugin.json generated by build', () => {
    const pluginPath = join(pluginRoot, 'adapters', 'claude', '.claude-plugin', 'plugin.json');
    const plugin = JSON.parse(readFileSync(pluginPath, 'utf8'));
    assert.equal(plugin.name, 'e2e-test');
    assert.equal(plugin.version, '0.1.0');
    assert.ok(typeof plugin.author === 'object', 'adapter plugin.json author must be object');
    assert.equal(plugin.skills, './skills/');
  });
});
